# Generated by Django 5.1.3 on 2025-03-27 17:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=1000)),
                ('price_per_night', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_guests', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('landlord_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
        migrations.CreateModel(
            name='OfferTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OfferDetails',
            fields=[
                ('offer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.offers')),
                ('private_bathroom', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('fridge_in_room', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('smoking_allowed', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('sauna', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('rooms', models.IntegerField(default=1)),
                ('beds', models.IntegerField(default=0)),
                ('double_beds', models.IntegerField(default=0)),
                ('sofa_beds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OfferImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False)),
                ('path', models.FileField(upload_to='images/')),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offers')),
            ],
        ),
        migrations.CreateModel(
            name='OfferLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('province', models.CharField(default='', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offers')),
            ],
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offertypes'),
        ),
    ]
