# Generated by Django 5.1.3 on 2025-03-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='offer_type_id',
        ),
        migrations.AddField(
            model_name='offers',
            name='offer_types',
            field=models.ManyToManyField(to='offers.offertypes'),
        ),
    ]
