# Generated by Django 5.1.3 on 2025-03-30 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offerlocation_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offer_main_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='main_offer_type', to='offers.offertypes'),
        ),
    ]
